// dart
import 'package:flutter/material.dart';
import 'firebase_config.dart';

class ReportsFilterPage extends StatelessWidget {
  const ReportsFilterPage({Key? key}) : super(key: key);

  Future<void> _generateReport(BuildContext context) async {
    // Simulate report generation logic
    await FirebaseConfig.logEvent(
      eventType: 'report_generated',
      description: 'Report generated by user',
      details: {
        'timestamp': DateTime.now().toIso8601String(),
      },
    );
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(content: Text('Report generated and logged')),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Reports Filter')),
      body: Center(
        child: ElevatedButton(
          onPressed: () => _generateReport(context),
          child: Text('Generate Report'),
        ),
      ),
    );
  }
}
